Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sneha_S_301096645.Models;

namespace Sneha_S_301096645.Controllers
{
    public class PlayerController : Controller
    {
        private IPlayerRepository repository;
        public PlayerController(IPlayerRepository repo)
        {
            repository = repo;
        }
        
        [Authorize]
        [HttpGet]
        [Route("/Player/ManagePlayers/{id?}")]
        public ViewResult ManagePlayers()
        {         
            return View();
        }
        
        [Authorize]
        [HttpPost]
        public ViewResult ManagePlayers(PlayerResponse player)
        {
            repository.SavePlayer(player);
            return View("PlayerDetails", repository.Players);
        }

        public ViewResult PlayerDetails(int id)
        {
            return View("PlayerDetails", repository.Players.Where(c => c.ClubID == id));
        }
    }
}

Views/Shared/ClubDetails.cshtml
@model IEnumerable<ClubResponse>
    
@{
     ViewBag.Title = "All Clubs"; Layout = "_Layout";
 }
     
<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th class="text-right">Manager</th>
        <th class="text-center">Actions</th>        
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.ClubID</td>
            <td>@item.ClubName</td>
            <td class="text-right">@item.ManagerName</td>
            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a asp-action="Edit" class="btn btn-sm btn-warning" asp-route-clubId="@item.ClubID">Edit</a>
                    <input type="hidden" name="ClubID" value="@item.ClubID" />
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    <a asp-action="PlayerDetails" class="btn btn-sm btn-warning"
                       asp-route-id="@item.ClubName" asp-controller="Player">
                        Players
                    </a>
                </form>
                <a asp-action="ManagePlayers" asp-controller="Player" class="btn btn-sm btn-warning" asp-route-id="@item.ClubName">
                    Add Player
                </a>
            </td>
        </tr>
    }
</table>

Views/Shared/InputPartial.cshtml
@model ClubResponse

<div asp-validation-summary="All"> </div>

<p>
    <label asp-for="ClubName">Club name:</label>
    <input asp-for="ClubName" />
</p>

<p>
    <label asp-for="Location">Location:</label>
    <input asp-for="Location" />
</p>
<p>
    <label asp-for="ManagerName">Name of Manager:</label>
    <input asp-for="ManagerName" />
</p>

Views/Shared/ManagePlayers.cshtml
@model PlayerResponse

@{
    ViewBag.Title = "Manage Players";
}

<div class="addclub">
    <form method="post" asp-action="ManagePlayers">
        <div asp-validation-summary="All"> </div>
        <p>
            <label asp-for="PlayerName">Player name:</label>
            <input asp-for="PlayerName" />
        </p>     
        <p>
            <label asp-for="Email">Email: </label>
            <input asp-for="Email" />
        </p>      
        <p>
            <label asp-for="ClubID">Club ID:</label>
            <input asp-for="ClubID" />
        </p>      
        <button type="submit">Submit</button>
    </form>
</div>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <link href="~/css/Styles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
    <header>
        <div class="logo">
            <img src="~/Images/logo.png" />"
        </div>
        <div class=" addclub">
            <div class="bg-info p-2 row">
                <div class="col">
                    <h2>@ViewBag.Title</h2>
                </div>

                <div class="col-2">
                    <a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">Log Out</a>
                </div>
            </div>
        </div>
        @if (TempData["message"] != null)
        {<div class="alert alert-success mt-1">@TempData["message"]</div>}
        @RenderBody()
    </header>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/Styles.css" rel="stylesheet" />  
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="logo">
            <img src="~/Images/logo.png" />"
        </div>        
        @if (TempData["message"] != null)
        {<div class="alert alert-success">@TempData["message"]</div>}
        <div class="row">
            <ul class="main-nav">
                <li><a asp-action="Index">HOME</a> </li>
                <li><a asp-action="Clubs">CLUBS</a></li>
                <li><a asp-action="AddClub">ADD CLUB</a></li>
                <li><a asp-action="ClubDetails">CLUB DETAILS</a></li>
            </ul>
        </div>
        <div>
            @RenderBody()
        </div>
    </header>
</body>
</html>